Kết nối database
 C:\laragon\www\DATNMOI> git rebase --abort
 PS C:\laragon\www\DATNMOI> git pull origin main --rebase
 From https://github.com/dungldph38549/DATNMOI
  * branch            main       -> FETCH_HEAD
  Auto-merging BE/index.js
  CONFLICT (content): Merge conflict in BE/index.js
  error: could not apply 5a0b8bd... Kết nối database
  Kết nối database

  # Please enter the commit message for your changes. Lines starting
  # with '#' will be ignored, and an empty message aborts the commit.
  #
  # interactive rebase in progress; onto e927a7f
  .git/COMMIT_EDITMSG [unix] (22:19 04/03/2026)
  1,1 Top
  "/c/laragon/www/DATNMOI/.git/COMMIT_EDITMSG" [unix] 584L, 36699Bm
PS C:\laragon\www\DATNMOI> git pull origin main --rebase
From https://github.com/dungldph38549/DATNMOI
 * branch            main       -> FETCH_HEAD
Auto-merging BE/index.js
CONFLICT (content): Merge conflict in BE/index.js
error: could not apply 5a0b8bd... Kết nối database
Kết nối database

.git/COMMIT_EDITMSG [unix] (22:19 04/03/2026)                                                          1,1 Top
"/c/laragon/www/DATNMOI/.git/COMMIT_EDITMSG" [unix] 584L, 36699Bm#